### ISSUE TITLE
questions about commit names

### ISSUE THREAD

**Issue by qqgg231** [Artificial-University/adblock-proxy#15]
@cookiengineer , do you have any script which helps you placing emojis in commit names?

I am under impression :-)

**Comment by cookiengineer** [comment]
Most of my projects follow the [git commit emojis](https://github.com/Artificial-Engineering/lycheejs/blob/development/guides/contributor/workflow.md#git-commit-messages) of the lychee.js Engine project.

I kinda adopted it pretty much everywhere, as the emojis represent the kind of feature that was implemented in that commit. So when browsing in a git UI, you can see each folder and its "stable/unstable/buggy" state easily.

So I also integrated it in my [dotvim](https://github.com/cookiengineer/dotvim), but VIM is not for everybody. Maybe in future it makes sense to have something like a small CLI wizard that allows you to select the type of commit that you are committing, before the actual message is then appended or so.

Not sure whether that answers your question? If not, please ask! :)
