### ISSUE TITLE
refactor working? getting 'proxy refusing connections'.

### ISSUE THREAD

**Issue by Aracktus** [Artificial-University/adblock-proxy#7]
Is the refactor'd code working for anyone?  I try to connect to the IP:port and get 'proxy refusing connections' in FF.

**Comment by vdergachev** [comment]
no)))))

**Comment by martensms** [comment]
Can you please try after [this commit](https://github.com/LazerUnicorns/adblock-proxy/commit/7125dd2198e94526051ba9c6fc1e296747d6f73c)?

Note that the parameters have changed and I still have no letsencrypt SSL support (which is blocking for the HTTPS proxy).

Also, I'm working on default bindings of the public=false mode. This is currently not implemented, so it's defaulted to public behaviour. If you set the HTTP proxy, it works on my machine. All rules are parsed properly and if I test it with typical websites (like the German spiegel.de website) the 410 Gone headers are correctly transferred by the adblock proxy.

Syntax for starting the proxy process is now:

```bash
cd /path/to/adblock-proxy;
./bin/proxy --public=true; # The public flag is optional, defaulted to true
```

**Comment by martensms** [comment]
Update: Can you try out one of the releases I just published [in the releases section](https://github.com/LazerUnicorns/adblock-proxy/releases/tag/v0.0.1) to verify the behaviour?
